# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGX_PDPGuuXAhUlh_c0_5PE0M-4EcEVg
"""

!pip install streamlit
!wget -q -O cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared.deb

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import random
# 
# # Player database
# players = {
#     "Virat Kohli": {"role": "Batsman", "points": 92},
#     "Jasprit Bumrah": {"role": "Bowler", "points": 85},
#     "Hardik Pandya": {"role": "All-Rounder", "points": 75},
#     "MS Dhoni": {"role": "Wicket Keeper", "points": 90},
#     "Rohit Sharma": {"role": "Batsman", "points": 88},
#     "Shubman Gill": {"role": "Batsman", "points": 80},
#     "Ravindra Jadeja": {"role": "All-Rounder", "points": 82},
#     "KL Rahul": {"role": "Wicket Keeper", "points": 83},
#     "Mohammed Shami": {"role": "Bowler", "points": 78},
#     "Rinku Singh": {"role": "Batsman", "points": 76}
# }
# 
# # Team generator
# def generate_team(n=3):
#     team = random.sample(list(players.keys()), n)
#     return {p: players[p] for p in team}
# 
# # App UI
# st.set_page_config(page_title="Fantasy Cricket Chatbot", page_icon="🏏")
# 
# st.title("🏏 Fantasy Cricket Chatbot Assistant")
# st.markdown("Welcome to your AI-powered team selector! 🤖 Ask me for suggestions or explore the player list.")
# 
# # Sidebar info
# with st.sidebar:
#     st.header("📘 About")
#     st.markdown("""
#     - 🔮 **Ask for 'team suggestion'** to get a random fantasy team.
#     - 🧠 Each player has roles and points.
#     - 🚀 Built with Streamlit + AI logic.
#     """)
#     st.info("Tip: Try clicking the 'Generate New Team' button below!")
# 
# # Text input
# user_input = st.text_input("💬 Ask me something (e.g., 'team suggestion')")
# 
# # Filter by role
# filter_role = st.selectbox("Filter players by role (optional):", ["All", "Batsman", "Bowler", "All-Rounder", "Wicket Keeper"])
# 
# # Show all players (filtered)
# st.subheader("📋 Available Players:")
# for name, info in players.items():
#     if filter_role == "All" or info["role"] == filter_role:
#         st.markdown(f"- **{name}** — *{info['role']}*, Points: `{info['points']}`")
# 
# st.markdown("---")
# 
# # Generate team
# if user_input and "team suggestion" in user_input.lower():
#     team = generate_team()
#     total_points = sum(info["points"] for info in team.values())
# 
#     st.success("🎉 Here's your fantasy team:")
#     for player, info in team.items():
#         st.markdown(f"- **{player}** — {info['role']} ({info['points']} pts)")
# 
#     st.markdown(f"**Total Team Points**: `{total_points}`")
# 
#     if st.button("🔁 Generate New Team"):
#         st.rerun()
# else:
#     if user_input:
#         st.warning("⚠️ Try asking: **team suggestion**")
# 
# 
#

!streamlit run app.py &>/content/log.txt &

!cloudflared tunnel --url http://localhost:8501